import CoreMotion
import Flutter
import UIKit

/// Activity recognition for iOS, backed by `CMMotionActivityManager`.
///
/// The Dart <-> native contract is generated by Pigeon from `pigeons/messages.dart`;
/// see `Messages.g.swift`. Configuration arrives over a host API and detections are
/// pushed back over an event channel.
public class ActivityRecognitionFlutterPlugin: NSObject, FlutterPlugin, ActivityRecognitionHostApi {
  private let streamHandler = ActivityStreamHandler()

  public static func register(with registrar: FlutterPluginRegistrar) {
    let plugin = ActivityRecognitionFlutterPlugin()

    ActivityRecognitionHostApiSetup.setUp(
      binaryMessenger: registrar.messenger(),
      api: plugin
    )
    StreamActivitiesStreamHandler.register(
      with: registrar.messenger(),
      streamHandler: plugin.streamHandler
    )

    registrar.publish(plugin)
  }

  // MARK: - ActivityRecognitionHostApi

  /// `runForegroundService` is Android-only: `CMMotionActivityManager` already
  /// delivers updates while the app is in the background, so there is nothing
  /// to configure on iOS.
  func configure(configuration: TrackingConfiguration) throws {}
}

/// Bridges `CMMotionActivityManager` updates onto the Pigeon event channel.
final class ActivityStreamHandler: StreamActivitiesStreamHandler {
  private let activityManager = CMMotionActivityManager()
  private let updateQueue = OperationQueue()

  override func onListen(withArguments arguments: Any?, sink: PigeonEventSink<PlatformActivity>) {
    guard CMMotionActivityManager.isActivityAvailable() else {
      sink.error(
        code: "UNAVAILABLE",
        message: "Motion activity is not available on this device.",
        details: nil
      )
      sink.endOfStream()
      return
    }

    activityManager.startActivityUpdates(to: updateQueue) { activity in
      guard let activity else { return }

      let event = PlatformActivity(
        type: Self.activityType(of: activity),
        confidence: Self.confidence(of: activity),
        timestamp: Int64(activity.startDate.timeIntervalSince1970 * 1000)
      )

      // Event sinks must be driven from the platform thread.
      DispatchQueue.main.async { sink.success(event) }
    }
  }

  override func onCancel(withArguments arguments: Any?) {
    activityManager.stopActivityUpdates()
  }

  /// `CMMotionActivity` exposes independent flags that may be set at the same
  /// time, so they are checked in priority order and the first match wins.
  private static func activityType(of activity: CMMotionActivity) -> PlatformActivityType {
    if activity.stationary { return .still }
    if activity.walking { return .walking }
    if activity.running { return .running }
    if activity.automotive { return .inVehicle }
    if activity.cycling { return .onBicycle }
    return .unknown
  }

  /// Maps the three-level iOS confidence onto the 0-100 scale Android reports.
  private static func confidence(of activity: CMMotionActivity) -> Int64 {
    switch activity.confidence {
    case .low: return 10
    case .medium: return 50
    case .high: return 100
    @unknown default: return 0
    }
  }
}
