package dk.carp.activity_recognition_flutter

import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import com.google.android.gms.location.ActivityRecognition
import io.flutter.embedding.engine.plugins.FlutterPlugin

/**
 * Activity recognition for Android, backed by the Google Play services
 * Activity Recognition API.
 *
 * The Dart <-> native contract is generated by Pigeon from `pigeons/messages.dart`;
 * see `Messages.g.kt`. Configuration arrives over a host API and detections are
 * pushed back over an event channel.
 *
 * Detections are delivered by the system to [ActivityRecognizedBroadcastReceiver],
 * which may run without a Flutter engine attached, so they reach this plugin
 * through [DetectedActivityStore].
 */
class ActivityRecognitionFlutterPlugin :
    FlutterPlugin,
    ActivityRecognitionHostApi,
    SharedPreferences.OnSharedPreferenceChangeListener {

    private companion object {
        const val TAG = "ActivityRecognition"

        /** How often the system is asked for a new detection. */
        const val DETECTION_INTERVAL_MS = 5_000L
    }

    private val mainHandler = Handler(Looper.getMainLooper())
    private val streamHandler = ActivityStreamHandler()

    private var applicationContext: Context? = null
    private var preferences: SharedPreferences? = null
    private var eventSink: PigeonEventSink<PlatformActivity>? = null
    private var runForegroundService = false

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        val context = binding.applicationContext
        applicationContext = context

        ActivityRecognitionHostApi.setUp(binding.binaryMessenger, this)
        StreamActivitiesStreamHandler.register(binding.binaryMessenger, streamHandler)

        preferences = DetectedActivityStore.preferences(context).also {
            it.registerOnSharedPreferenceChangeListener(this)
        }
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        stopTracking()

        preferences?.unregisterOnSharedPreferenceChangeListener(this)
        preferences = null

        ActivityRecognitionHostApi.setUp(binding.binaryMessenger, null)
        applicationContext = null
    }

    // MARK: - ActivityRecognitionHostApi

    override fun configure(configuration: TrackingConfiguration) {
        runForegroundService = configuration.runForegroundService
    }

    // MARK: - Tracking

    private fun startTracking() {
        val context = applicationContext ?: return

        if (runForegroundService) {
            context.startForegroundService(Intent(context, ForegroundService::class.java))
        }

        ActivityRecognition.getClient(context)
            .requestActivityUpdates(DETECTION_INTERVAL_MS, detectionIntent(context))
            .addOnSuccessListener { Log.d(TAG, "Registered for activity updates.") }
            .addOnFailureListener { Log.e(TAG, "Could not register for activity updates.", it) }
    }

    private fun stopTracking() {
        val context = applicationContext ?: return

        ActivityRecognition.getClient(context).removeActivityUpdates(detectionIntent(context))

        if (runForegroundService) {
            context.stopService(Intent(context, ForegroundService::class.java))
        }
    }

    private fun detectionIntent(context: Context): PendingIntent {
        val intent = Intent(context, ActivityRecognizedBroadcastReceiver::class.java)

        var flags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // The Activity Recognition API writes the detection result into this
            // intent, so it has to stay mutable on API 31 and above.
            flags = flags or PendingIntent.FLAG_MUTABLE
        }

        return PendingIntent.getBroadcast(context, 0, intent, flags)
    }

    // MARK: - Detections arriving from the broadcast receiver

    override fun onSharedPreferenceChanged(preferences: SharedPreferences?, key: String?) {
        if (key != DetectedActivityStore.KEY_DETECTED_ACTIVITY) return

        val sink = eventSink ?: return
        val activity = preferences?.let(DetectedActivityStore::read) ?: return

        // Event sinks have to be driven from the main thread, and preference
        // changes are published on whichever thread wrote them.
        mainHandler.post { sink.success(activity) }
    }

    private inner class ActivityStreamHandler : StreamActivitiesStreamHandler() {
        override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformActivity>) {
            eventSink = sink
            startTracking()
        }

        override fun onCancel(p0: Any?) {
            stopTracking()
            eventSink = null
        }
    }
}
