// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// The activity types that can be reported by the native platforms.
///
/// Android reports these directly; the smaller set of iOS `CMMotionActivity`
/// flags is mapped onto them natively, so the wire format is identical on
/// both platforms.
enum PlatformActivityType {
  inVehicle,
  onBicycle,
  onFoot,
  running,
  still,
  tilting,
  unknown,
  walking,
}

/// A single activity detection as reported by the platform.
class PlatformActivity {
  PlatformActivity({
    required this.type,
    required this.confidence,
    required this.timestamp,
  });

  /// The detected activity.
  PlatformActivityType type;

  /// Confidence of the detection, in percent (0-100).
  int confidence;

  /// When the activity was detected, in milliseconds since the Unix epoch.
  ///
  /// Produced natively so the timestamp reflects the detection itself rather
  /// than the moment the event happened to arrive in Dart.
  int timestamp;

  List<Object?> _toList() {
    return <Object?>[
      type,
      confidence,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformActivity decode(Object result) {
    result as List<Object?>;
    return PlatformActivity(
      type: result[0]! as PlatformActivityType,
      confidence: result[1]! as int,
      timestamp: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformActivity || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(confidence, other.confidence) && _deepEquals(timestamp, other.timestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformActivity(type: $type, confidence: $confidence, timestamp: $timestamp)';
  }
}

/// Options applied to activity tracking before the event stream is started.
class TrackingConfiguration {
  TrackingConfiguration({
    required this.runForegroundService,
  });

  /// Whether Android should run a foreground service so that detections keep
  /// arriving while the app is backgrounded.
  ///
  /// Ignored on iOS, where `CMMotionActivityManager` already delivers updates
  /// in the background.
  bool runForegroundService;

  List<Object?> _toList() {
    return <Object?>[
      runForegroundService,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrackingConfiguration decode(Object result) {
    result as List<Object?>;
    return TrackingConfiguration(
      runForegroundService: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runForegroundService, other.runForegroundService);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackingConfiguration(runForegroundService: $runForegroundService)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformActivityType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformActivity) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TrackingConfiguration) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformActivityType.values[value];
      case 130:
        return PlatformActivity.decode(readValue(buffer)!);
      case 131:
        return TrackingConfiguration.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Control channel. Called before listening to [ActivityStreamApi].
class ActivityRecognitionHostApi {
  /// Constructor for [ActivityRecognitionHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ActivityRecognitionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Applies [configuration] to the next tracking session.
  Future<void> configure(TrackingConfiguration configuration) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.activity_recognition_flutter.ActivityRecognitionHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[configuration]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Data channel carrying the detected activities.
/// Returns a broadcast [Stream] of events from the `streamActivities` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformActivity> streamActivities( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamActivitiesChannel =
      EventChannel('dev.flutter.pigeon.activity_recognition_flutter.ActivityStreamApi.streamActivities$instanceName', pigeonMethodCodec);
  return streamActivitiesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformActivity;
  });
}
    
