name: light
description: Plugin for collecting data from the ambient light sensor on Android and iOS.
version: 5.0.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master

environment:
  sdk: ^3.6.0
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  config:
    enable-swift-package-manager: true
  plugin:
    platforms:
      android:
        package: dk.cachet.light
        pluginClass: LightPlugin
      ios:
        pluginClass: LightPlugin
